accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('edit/', views.edit, name='edit'),
    path('delete/', views.delete, name='delete'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('<int:board_pk>/edit/', views.update, name='update'),
    path('<int:board_pk>/delete/', views.delete, name='delete'),
    path('<int:board_pk>/', views.detail, name='detail'),
    path('new/', views.create, name='create'),
    path('', views.index, name='index')
]

myform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

boards/models.py
from django.db import models

# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User

class UserCustomChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name',]

boards/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import Board

# class BoardForm(forms.Form):
#     title = forms.CharField(label='제목 ', widget=forms.TextInput(attrs={
#                                                     'placeholder' : 'What is The Title ?',
#     }))
#     content = forms.CharField(label='내용',
#                                 error_messages={'required' : '제발 내용을 넣어주세요'}, 
#                                 widget=forms.Textarea(attrs={
#                                         'class' : 'Content-input',
#                                         'rows' : 5,
#                                         'cols' : 50,
#                                         'placeholder' : 'Fill the content'
#                                                                             }))

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = '__all__'
        widgets = {'title' : forms.TextInput(attrs={
            'placeholder' : '제목을 입력하세요',
            'class' : 'title'}),
            'content' : forms.Textarea(attrs={
                'placeholder' : '내용을 입력하세요',
                'classs' : 'content',
                'rows' : 5,
                'cols' : 50,})}
        error_messages = {'title' : {'required' : '제발 입력해 주세요.'},
                            'content' : {'required' : '내용 입력하세요.'}}
    
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('submit', '작성!'))

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import UserCustomChangeForm

# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('boards:index')
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('boards:index')
    else:
        form = UserCreationForm()
    context = {'form' : form}
    return render(request, 'accounts/signup.html', context)
    
def login(request):
    if request.user.is_authenticated:
        return redirect('boards:index')
    if request.method =="POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('boards:index')
    else:
        form = AuthenticationForm()
    context = {"form":form}
    return render(request, 'accounts/login.html', context)
    
def logout(request):
    auth_logout(request)
    return redirect('boards:index')
    
def delete(request):
    user = request.user
    if request.method =="POST":
        # DELETE
        user.delete()
        # 유저가 삭제되면 자동으로 장고 내에서 세션이 삭제됨.
        # 로그아웃 해 줄 필요가 없음.
    return redirect('boards:index')
    
def edit(request):
    if request.method == "POST":
        # 수정 진행
        form = UserCustomChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('boards:index')
    else:
        form = UserCustomChangeForm(instance=request.user)
    context = {'form':form}
    return render(request, 'accounts/edit.html', context)

boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Board
from .forms import BoardForm

# Create your views here.
def index(request):
    boards = Board.objects.order_by('-pk')
    context = {'boards':boards}
    return render(request, 'boards/index.html', context)
    
def create(request):
    # post 요청이면 form데이터를 처리한다.
    if request.method == "POST":
        #  이 처리 과정은 'binding'이라고 불리는데, 폼의 유효성 체크를 할 수 있도록 해준다.
        form = BoardForm(request.POST)
        # form 유효성 체크
        if form.is_valid():
        # cleaned_data : 유효성검증을 위한 것.
            board = form.save()
            return redirect('boards:detail', board.pk)
            # title = form.cleaned_data.get('title')
            # content = form.cleaned_data.get('content')
            # # 검증을 통과한 데이터로 보드를 만든다.
            # board = Board.objects.create(title=title, content=content)
            # return redirect('boards:detail', board.pk)
    # post가 아닌 요청이면 기본 폼을 생성한다.
    else:
        form = BoardForm()
    context = {'form':form}
    return render(request, 'boards/form.html', context)
        
def detail(request, board_pk):
    # board = Board.objects.get(pk=board_pk)
    board = get_object_or_404(Board, pk=board_pk)
    context = {'board':board}
    return render(request, 'boards/detail.html', context)
    
def delete(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if request.method == "POST":
        board.delete()
        return redirect('boards:index')
    else:
        return redirect('boards:detail', board.pk)
        
def update(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if request.method == "POST":
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            board = form.save()
            return redirect('boards:detail', board.pk)
    # get 요청이면(혹은 수정하기 버튼을 눌렀을 떄)
    else:
        
        # 원래는 이렇게 써야 함
        # form = BoardForm(initial={'title' : board.title, 'content':board.content})
        # boardForm을 초기화(사용자 입력 값을 넣어준 상태로)
        # form 
        form = BoardForm(instance=board)
    context = {'form' : form, 'board':board}
    # POST :  요청에서 검증에 실패하였을때, 오류메시지가 포함된 상태
    # GET : 요청에서 초기화 된 상태.
    return render(request, 'boards/form.html', context)

accounts/templates/accounts/edit.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}
<h1>회원정보 수정</h1>
<form method="POST">
    {% csrf_token %}
    {{ form | crispy }}
    <input type="submit" value="Submit"/>
</form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}
<h1>로그인</h1>
<form method="POST">
    {% csrf_token %}
    {{ form | crispy }}
    <input type="submit" value="Submit"/>
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}
    <h1>회원가입</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form | crispy }}
        <input type="submit" value="submit"/>
    </form>
{% endblock %}

boards/templates/boards/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        {% if user.is_authenticated %}
            안녕, {{ user.username }}
            <a href="{% url 'accounts:edit' %}">정보수정</a>
            <a href="{% url 'accounts:logout' %}">로그아웃</a>
            <form action="{% url 'accounts:delete' %}" method="POST" style="display:inline" onsubmit="return confirm('R U sure?');">
                {% csrf_token %}
                <input type="submit" value="탈퇴"/>
            </form>
        {% else %}
            <h3>
                <a href="{% url 'accounts:login' %}">로그인</a>
                <a href="{% url 'accounts:signup' %}">회원가입</a>
            </h3>
        {% endif %}
        <hr>
        {% block body %} {% endblock %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </div>
</body>

</html>

boards/templates/boards/detail.html
{% extends 'boards/base.html' %}
{% block body %}
<h1>{{ board.pk }}번째 글</h1>
<h2>{{ board.title }}</h2>
<hr>
<p>{{ board.content }}</p>
<a href="{% url 'boards:index' %}">[뒤로]</a>
<form action="{% url 'boards:delete' board.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제"/>
</form>
<a href="{% url 'boards:update' board.pk %}">[수정]</a>
{% endblock %}

boards/templates/boards/form.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}


{% if request.resolver_match.url_name == 'create' %}
    <h1>NEW board</h1>
{% else %}
    <h1>EDIT board</h1>
{% endif %}

<!--<form method="POST">-->
<!--    {% csrf_token %}-->
<!--    {{ form.as_p }}-->
<!--    <input type="submit" value="Submit"/>-->
<!--</form>-->


<form method="POST">
    {% csrf_token %}
    {{ form | crispy }}
    <input type="submit" value="Submit"/>
</form>


<!--<form method="POST">-->
<!--    {% csrf_token %}-->
<!--    {% for field in form %}-->
<!--        {{ field.error }}-->
<!--        {{ field.label_tag }} {{ field }}-->
<!--    {% endfor %}-->
<!--    <input type="submit" value="Submit"/>-->
<!--</form>-->

<!--{{ field.non_field_errors }}-->
<!--<form method="POST">-->
<!--    {% csrf_token %}-->
<!--    <div>-->
<!--        {{ form.title.errors }}-->
<!--        {{ form.title.label_tag }}-->
<!--        {{ form.title }}-->
<!--    </div>-->
<!--    <div>-->
<!--        {{ form.content.errors }}-->
<!--        {{ form.content.label_tag }}-->
<!--        {{ form.content }}-->
<!--    </div>-->
<!--    <input type="submit" value="Submit"/>-->
<!--</form>-->


<!--{% crispy form %}-->



{% if request.resolver_match.url_name == 'create' %}
    <a href="{% url 'boards:index' %}">[BACK]</a>
{% else %}
    <a href="{% url 'boards:detail' board.pk %}">[BACK]</a>
{% endif %}


{% endblock %}

boards/templates/boards/index.html
{% extends 'boards/base.html' %}
{% block body%}
<h1>게시글 목록</h1>
{% if user.is_authenticated %}
    <a href="{% url 'boards:create' %}">새 글 작성</a>
{% else %}
    <a href="{% url 'accounts:login' %}">새 글을 작성하려면 로그인 하세요</a>
{% endif %}
{% for board in boards %}
    <p>{{ board.pk }}</p>
    <p>{{ board.title }}</p>
    <a href="{% url 'boards:detail' board.pk %}">글 보러 가기</a>
    <hr>
{% endfor %}
{% endblock %}